£ Mame a copy of the dataset
BRFSS_m <- BRFSS_l

£ Flag the born gender

BRFSS_m$MALE <- 0
BRFSS_m$MALE[BRFSS_m$X_SEX == 1] <-1

table(BRFSS_m$X_SEX, BRFSS_m$X_SEX)

£ Mame exercise variables

BRFSS_m$EXERGRP <- 9
BRFSS_m$EXERGRP[BRFSS_m$EXERANY2 == 1] <- 1
BRFSS_m$EXERGRP[BRFSS_m$EXERANY2 == 2] <- 0

table(BRFSS_m$EXERANY2, BRFSS_m$EXERGRP)

£ Mame merital variables

BRFSS_m$MARGRP <- 9
BRFSS_m$MARGRP[BRFSS_m$MARITAL == 1 | BRFSS_m$MARITAL == 6] <- 1
BRFSS_m$MARGRP[BRFSS_m$MARITAL == 2 | BRFSS_m$MARITAL == 3 | BRFSS_m$MARITAL == 4] <- 2
BRFSS_m$MARGRP[BRFSS_m$MARITAL == 5] <- 3

table(BRFSS_m$MARITAL, BRFSS_m$MARGRP)

BRFSS_m$NEVERMAR <-0
BRFSS_m$FORMERMAR <-0

BRFSS_m$NEVERMAR[BRFSS_m$MARGRP == 3] <-1
table(BRFSS_m$MARGRP, BRFSS_m$NEVERMAR)

BRFSS_m$FORMERMAR[BRFSS_m$MARGRP == 2] <-1
table(BRFSS_m$MARGRP, BRFSS_m$FORMERMAR)


£ Make education variables

BRFSS_m$EDGOUP <- 9
BRFSS_m$EDGOUP[BRFSS_m$EDUCA == 1 | BRFSS_m$EDUCA == 2 | BRFSS_m$EDUCA == 3] <- 1
BRFSS_m$EDGOUP[BRFSS_m$EDUCA == 4] <- 2
BRFSS_m$EDGOUP[BRFSS_m$EDUCA == 5] <- 3
BRFSS_m$EDGOUP[BRFSS_m$EDUCA == 6] <- 4
table(BRFSS_m$EDUCA, BRFSS_m$EDGOUP)

BRFSS_m$LOWED <- 1
BRFSS_m$SOMECOLL <- 0
BRFSS_m$LOWED[BRFSS_m$EDGOUP == 3 | BRFSS_m$EDGOUP == 4] <- 0
BRFSS_m$LOWED[BRFSS_m$EDGOUP == 9] <- 9
table(BRFSS_m$EDGOUP, BRFSS_m$LOWED)
BRFSS_m$SOMECOLL[BRFSS_m$EDGOUP == 3] <- 1
BRFSS_m$SOMECOLL[BRFSS_m$EDGOUP == 9] <- 9
table(BRFSS_m$EDGOUP, BRFSS_m$SOMECOLL)

£ Make income variables

BRFSS_m$INC1 <- 0
BRFSS_m$INC2 <- 0
BRFSS_m$INC3 <- 0
BRFSS_m$INC4 <- 0
BRFSS_m$INC5 <- 0
BRFSS_m$INC6 <- 0
BRFSS_m$INC7 <- 0
BRFSS_m$INC8 <- 0
BRFSS_m$INC9 <- 0
BRFSS_m$INC10 <- 0
BRFSS_m$INC11 <- 0




BRFSS_m$INC1[BRFSS_m$INCOME3 == 1] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC1)

BRFSS_m$INC2[BRFSS_m$INCOME3 == 2] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC2)

BRFSS_m$INC3[BRFSS_m$INCOME3 == 3] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC3)

BRFSS_m$INC4[BRFSS_m$INCOME3 == 4] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC4)

BRFSS_m$INC5[BRFSS_m$INCOME3 == 5] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC5)

BRFSS_m$INC6[BRFSS_m$INCOME3 == 6] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC6)

BRFSS_m$INC7[BRFSS_m$INCOME3 == 7] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC7)

BRFSS_m$INC8[BRFSS_m$INCOME3 == 8] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC8)

BRFSS_m$INC9[BRFSS_m$INCOME3 == 9] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC9)

BRFSS_m$INC10[BRFSS_m$INCOME3 == 10] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC10)

BRFSS_m$INC11[BRFSS_m$INCOME3 == 11] <-1
table(BRFSS_m$INCOME3, BRFSS_m$INC11)
